# AIRBNB_REVIEWS_
from .ExtractRapidapiAirbnbReviewsStatistics import STATISTICS as AIRBNB_REVIEWS_STATISTICS
from .ExtractRapidapiBookingReviewsStatistics import STATISTICS as BOOKING_REVIEWS_STATISTICS
from .ExtractRapidapiHotelsReviewsStatistics import STATISTICS as HOTELS_REVIEWS_STATISTICS
from .ExtractRapidapiPricelineReviewsStatistics import STATISTICS as PRICELINE_REVIEWS_STATISTICS
from .ExtractRapidapiBookingListingsStatistics import STATISTICS as BOOKING_LISTINGS_STATISTICS
from .ExtractRapidapiHotelsListingsStatistics import STATISTICS as HOTELS_LISTINGS_STATISTICS
from .ExtractRapidapiPricelineListingsStatistics import STATISTICS as PRICELINE_LISTINGS_STATISTICS

from .ExtractApifyStatistics import STATISTICS as APIFY_STATISTICS

from .ExtractSnowflakeFlightSchedulesStatistics import STATISTICS as SNOWFLAKE_FLIGHT_SCHEDULES_STATISTICS

from .ExtractTransparentListingsStatistics import STATISTICS as TRANSPARENT_LISTINGS_STATISTICS
from .ExtractTransparentOperationalStatistics import STATISTICS as TRANSPARENT_OPERATIONAL_STATISTICS
